name: x509b
description: Dart library for parsing and working with X.509 certificates.
version: 0.3.0
homepage: https://github.com/jeroentrappers/x509

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^1.0.0
  asn1lib: ^1.1.0
  quiver: ^3.0.0
  crypto_keys: '>=0.2.0 <0.4.0'

dev_dependencies:
  test: ^1.0.0
  pedantic: ^1.9.0

